/**
 * Configuration from process.env only. Names derive from CRM properties/v2.ts keys via envKey():
 * Admin_email -> ADMIN_EMAIL, printLogsToConsole -> PRINT_LOGS_TO_CONSOLE.
 * Set in .env locally and Railway variables.
 */

/** Railway/.env variable name for a v2.ts property key. */
export function envKey(propKey: string): string {
  return propKey.replace(/([a-z\d])([A-Z])/g, "$1_$2").toUpperCase();
}

/** Optional string from env (empty string treated as unset). */
function envString(propKey: string): string | undefined {
  const v = process.env[envKey(propKey)];
  return v === "" ? undefined : v;
}

function envBool(propKey: string): boolean | undefined {
  const v = process.env[envKey(propKey)];
  if (v === undefined || v === "") return undefined;
  const lower = v.toLowerCase();
  if (lower === "true" || lower === "1" || lower === "yes") return true;
  if (lower === "false" || lower === "0" || lower === "no") return false;
  return undefined;
}

function envNum(propKey: string): number | undefined {
  const v = process.env[envKey(propKey)];
  if (v === undefined || v === "") return undefined;
  const n = Number(v);
  return Number.isFinite(n) ? n : undefined;
}

/** JSON array (e.g. ["a","b"]) or comma-separated values. */
function envStringArray(propKey: string): string[] | undefined {
  const v = process.env[envKey(propKey)];
  if (v === undefined || v === "") return undefined;
  const trimmed = v.trim();
  if (trimmed.startsWith("[")) {
    try {
      const parsed: unknown = JSON.parse(trimmed);
      return Array.isArray(parsed) ? parsed.map(String) : undefined;
    } catch {
      return undefined;
    }
  }
  return trimmed.split(",").map((s) => s.trim()).filter(Boolean);
}

export const properties = {
  filePath: envString("filePath"),
  SampleFilePath: envString("SampleFilePath"),
  printLogsToConsole: envBool("printLogsToConsole"),
  persistPrintLogsToFile: envBool("persistPrintLogsToFile"),
  printLogsStorePath: envString("printLogsStorePath"),
  printLogFileName: envString("printLogFileName"),
  delete_files: envBool("delete_files"),
  getNumberFromServer: envBool("getNumberFromServer"),
  Phonelib_Random_Phone_Api_Key: envString("Phonelib_Random_Phone_Api_Key"),
  PASSWORD: envString("PASSWORD"),
  Admin_email: envString("Admin_email"),
  SalesManager_email: envString("SalesManager_email"),
  PreSales_email: envString("PreSales_email"),
  PreSales_email2: envString("PreSales_email2"),
  PreSalesManager_email: envString("PreSalesManager_email"),
  EditUserMail: envString("EditUserMail"),
  SM_00: envString("SM_00"),
  SM_01: envString("SM_01"),
  SM_02: envString("SM_02"),
  SM_03: envString("SM_03"),
  SM_04: envString("SM_04"),
  SM_05: envString("SM_05"),
  SM_06: envString("SM_06"),
  SM_07: envString("SM_07"),
  SM_08: envString("SM_08"),
  WF_Client_Id_01: envString("WF_Client_Id_01"),
  WF_Client_FullAccess_API_01: envString("WF_Client_FullAccess_API_01"),
  WF_Client_RestrictedAccess_API_01: envString("WF_Client_RestrictedAccess_API_01"),
  WF_Client_Id_02: envString("WF_Client_Id_02"),
  WF_Client_FullAccess_API_02: envString("WF_Client_FullAccess_API_02"),
  WF_Client_RestrictedAccess_API_02: envString("WF_Client_RestrictedAccess_API_02"),
  WF_Clinet_Sales_Email_02: envString("WF_Clinet_Sales_Email_02"),
  WF_Clinet_Sales_Id_02: envString("WF_Clinet_Sales_Id_02"),
  WF_Client_Id_03: envString("WF_Client_Id_03"),
  WF_Client_FullAccess_API_03: envString("WF_Client_FullAccess_API_03"),
  WF_Client_RestrictedAccess_API_03: envString("WF_Client_RestrictedAccess_API_03"),
  WF_Clinet_Sales_Email_03: envString("WF_Clinet_Sales_Email_03"),
  WF_Clinet_Sales_Id_03: envString("WF_Clinet_Sales_Id_03"),
  WF_Client_Id_04: envString("WF_Client_Id_04"),
  WF_Client_FullAccess_API_04: envString("WF_Client_FullAccess_API_04"),
  WF_Client_RestrictedAccess_API_04: envString("WF_Client_RestrictedAccess_API_04"),
  WF_Clinet_Sales_Email_04: envString("WF_Clinet_Sales_Email_04"),
  WF_Clinet_Sales_Id_04: envString("WF_Clinet_Sales_Id_04"),
  WF_Client_Id_05: envString("WF_Client_Id_05"),
  WF_Client_FullAccess_API_05: envString("WF_Client_FullAccess_API_05"),
  WF_Client_RestrictedAccess_API_05: envString("WF_Client_RestrictedAccess_API_05"),
  WF_Clinet_Sales_Email_05: envString("WF_Clinet_Sales_Email_05"),
  WF_Clinet_Sales_Id_05: envString("WF_Clinet_Sales_Id_05"),
  WF_Client_Id_06: envString("WF_Client_Id_06"),
  WF_Client_FullAccess_API_06: envString("WF_Client_FullAccess_API_06"),
  WF_Client_RestrictedAccess_API_06: envString("WF_Client_RestrictedAccess_API_06"),
  WF_Client_Id_07: envString("WF_Client_Id_07"),
  WF_Client_FullAccess_API_07: envString("WF_Client_FullAccess_API_07"),
  WF_Client_RestrictedAccess_API_07: envString("WF_Client_RestrictedAccess_API_07"),
  WF_Clinet_Sales_Email_07: envString("WF_Clinet_Sales_Email_07"),
  WF_Clinet_Sales_Id_07: envString("WF_Clinet_Sales_Id_07"),
  WF_Clinet_Project_Id_07: envString("WF_Clinet_Project_Id_07"),
  WF_Client_Id_08: envString("WF_Client_Id_08"),
  WF_Client_FullAccess_API_08: envString("WF_Client_FullAccess_API_08"),
  WF_Client_RestrictedAccess_API_08: envString("WF_Client_RestrictedAccess_API_08"),
  WF_Clinet_Sales_Email_08: envString("WF_Clinet_Sales_Email_08"),
  WF_Clinet_Sales_Id_08: envString("WF_Clinet_Sales_Id_08"),
  WF_Clinet_Project_Id_08: envString("WF_Clinet_Project_Id_08"),
  WF_Client_Doocti_Amura_VN_1: envString("WF_Client_Doocti_Amura_VN_1"),
  WF_Clinet_Sales_Email_06: envString("WF_Clinet_Sales_Email_06"),
  WF_Clinet_Sales_Id_06: envString("WF_Clinet_Sales_Id_06"),
  WF_Clinet_Project_Id_06_01: envString("WF_Clinet_Project_Id_06_01"),
  WF_Clinet_Project_Id_06_02: envString("WF_Clinet_Project_Id_06_02"),
  WF_Clinet_Project_Id_06_03: envString("WF_Clinet_Project_Id_06_03"),
  WF_Clinet_Project_Id_06_04: envString("WF_Clinet_Project_Id_06_04"),
  Whatsapp_Client_Id_01: envString("Whatsapp_Client_Id_01"),
  Whatsapp_Client_FullAccess_API_01: envString("Whatsapp_Client_FullAccess_API_01"),
  Whatsapp_Client_RestrictedAccess_API_01: envString("Whatsapp_Client_RestrictedAccess_API_01"),
  Whatsapp_Client_Sales_Email_01: envString("Whatsapp_Client_Sales_Email_01"),
  Whatsapp_Client_Sales_Id_01: envString("Whatsapp_Client_Sales_Id_01"),
  Inventory_Import_Client_Id_01: envString("Inventory_Import_Client_Id_01"),
  Inventory_Import_Client_FullAccess_API_01: envString("Inventory_Import_Client_FullAccess_API_01"),
  Inventory_Import_Client_RestrictedAccess_API_01: envString("Inventory_Import_Client_RestrictedAccess_API_01"),
  Inventory_Import_Client_Sales_Email_01: envString("Inventory_Import_Client_Sales_Email_01"),
  Inventory_Import_Client_Sales_Id_01: envString("Inventory_Import_Client_Sales_Id_01"),
  ES_Test_Client_Id_01: envString("ES_Test_Client_Id_01"),
  ES_Test_Client_FullAccess_API_01: envString("ES_Test_Client_FullAccess_API_01"),
  ES_Test_Client_RestrictedAccess_API_01: envString("ES_Test_Client_RestrictedAccess_API_01"),
  ES_Test_Client_Sales_Email_01: envString("ES_Test_Client_Sales_Email_01"),
  ES_Test_Client_Sales_Id_01: envString("ES_Test_Client_Sales_Id_01"),
  ES_Test_Client_Sales_Email_02: envString("ES_Test_Client_Sales_Email_02"),
  ES_Test_Client_Sales_Id_02: envString("ES_Test_Client_Sales_Id_02"),
  ES_Test_Client_Admin_Email_01: envString("ES_Test_Client_Admin_Email_01"),
  PC_Client_ID: envString("PC_Client_ID"),
  PC_Client_ID_FullAccess_API: envString("PC_Client_ID_FullAccess_API"),
  PC_Client_Admin_user: envString("PC_Client_Admin_user"),
  PC_Client_Sales_user: envString("PC_Client_Sales_user"),
  PC_Client_Postsale_user: envString("PC_Client_Postsale_user"),
  PT_ProjectName: envString("PT_ProjectName"),
  PT_TotalFloors: envString("PT_TotalFloors"),
  PT_StageName: envString("PT_StageName"),
  FP_DeveloperName: envString("FP_DeveloperName"),
  FP_ProjectName: envString("FP_ProjectName"),
  FP_TowerName: envString("FP_TowerName"),
  FP_UnitConfiguration: envString("FP_UnitConfiguration"),
  FP_UnitType: envString("FP_UnitType"),
  FP_UnitCategory: envString("FP_UnitCategory"),
  FP_Bedroom: envString("FP_Bedroom"),
  FP_Bathroom: envString("FP_Bathroom"),
  FP_Carpet: envString("FP_Carpet"),
  FP_Saleable: envString("FP_Saleable"),
  FP_Loading: envString("FP_Loading"),
  FP_TerraceArea: envString("FP_TerraceArea"),
  FP_CoveredArea: envString("FP_CoveredArea"),
  FP_BaseRate: envString("FP_BaseRate"),
  UN_DeveloperName: envString("UN_DeveloperName"),
  UN_ProjectName: envString("UN_ProjectName"),
  UN_TowerName: envString("UN_TowerName"),
  UN_UnitConfiguration: envString("UN_UnitConfiguration"),
  UN_FloorNumber: envString("UN_FloorNumber"),
  UN_AgreementValue: envString("UN_AgreementValue"),
  UN_AllInclusivePrice: envString("UN_AllInclusivePrice"),
  UN_MonthlyRent: envString("UN_MonthlyRent"),
  UN_MaintenanceAmount: envString("UN_MaintenanceAmount"),
  UN_SecurityAmount: envString("UN_SecurityAmount"),
  CP_Restricted_API: envString("CP_Restricted_API"),
  CP_FullAccess_API: envString("CP_FullAccess_API"),
  CP_Client_Id: envString("CP_Client_Id"),
  Project_Name: envString("Project_Name"),
  Project_id: envString("Project_id"),
  Project_Name_Rooted: envString("Project_Name_Rooted"),
  Project_id_Rooted: envString("Project_id_Rooted"),
  NonRootedProjectName01: envString("NonRootedProjectName01"),
  NonRootedProjectID01: envString("NonRootedProjectID01"),
  NonRootedProjectName02: envString("NonRootedProjectName02"),
  NonRootedProjectID02: envString("NonRootedProjectID02"),
  NonRootedProjectName03: envString("NonRootedProjectName03"),
  NonRootedProjectID03: envString("NonRootedProjectID03"),
  NonRootedProjectName04: envString("NonRootedProjectName04"),
  NonRootedProjectID04: envString("NonRootedProjectID04"),
  NonRootedProjectName05: envString("NonRootedProjectName05"),
  NonRootedProjectID05: envString("NonRootedProjectID05"),
  Project_Name_2: envString("Project_Name_2"),
  Project_id_2: envString("Project_id_2"),
  projectToKeepActive: envStringArray("projectToKeepActive"),
  Developer_id: envString("Developer_id"),
  Client_id: envString("Client_id"),
  FullAccess_API: envString("FullAccess_API"),
  RestrictedAccess_API: envString("RestrictedAccess_API"),
  Non_Rooted_Client_id: envString("Non_Rooted_Client_id"),
  Non_Rooted_FullAccess_API: envString("Non_Rooted_FullAccess_API"),
  Non_Rooted_RestrictedAccess_API: envString("Non_Rooted_RestrictedAccess_API"),
  Sales_id: envString("Sales_id"),
  Sales_email: envString("Sales_email"),
  Sales_name: envString("Sales_name"),
  salesPhone: envString("salesPhone"),
  Sales_id_Manager: envString("Sales_id_Manager"),
  Sales_id_SearchList: envString("Sales_id_SearchList"),
  Sales_Name_SearchList: envString("Sales_Name_SearchList"),
  Sales_Email_SearchList: envString("Sales_Email_SearchList"),
  Sales_id_userScore: envString("Sales_id_userScore"),
  Sales_Name_userScore: envString("Sales_Name_userScore"),
  Sales_Email_userScore: envString("Sales_Email_userScore"),
  PreSales_id: envString("PreSales_id"),
  PreSales_name: envString("PreSales_name"),
  PreSales_id2: envString("PreSales_id2"),
  PreSales_name2: envString("PreSales_name2"),
  PreSales_id_Manager: envString("PreSales_id_Manager"),
  New_Routing_Client_Doocti_VN_1: envString("New_Routing_Client_Doocti_VN_1"),
  New_Routing_Client_Doocti_VN_2: envString("New_Routing_Client_Doocti_VN_2"),
  New_Routing_Client_Doocti_VN_3: envString("New_Routing_Client_Doocti_VN_3"),
  New_Routing_Client_Id: envString("New_Routing_Client_Id"),
  New_Routing_Client_FullAccess_API: envString("New_Routing_Client_FullAccess_API"),
  New_Routing_Client_RestrictedAccess_API: envString("New_Routing_Client_RestrictedAccess_API"),
  New_Routing_Client_RestrictedAccess_API_Organic: envString("New_Routing_Client_RestrictedAccess_API_Organic"),
  Team_Name: envString("Team_Name"),
  Team_ID: envString("Team_ID"),
  Team_Name2: envString("Team_Name2"),
  teamHierarchyID: envString("teamHierarchyID"),
  Campeign: envString("Campeign"),
  Campeign_id: envString("Campeign_id"),
  Source: envString("Source"),
  SubSource: envString("SubSource"),
  OrganicCampeignID: envString("OrganicCampeignID"),
  CampaignNameForImportSRD: envString("CampaignNameForImportSRD"),
  CampaignIdForImportSRD: envString("CampaignIdForImportSRD"),
  srd1: envString("srd1"),
  srd1_name: envString("srd1_name"),
  srd2: envString("srd2"),
  srd2_name: envString("srd2_name"),
  DooctiVN: envString("DooctiVN"),
  Standard_Integration_VN: envString("Standard_Integration_VN"),
  SID: envString("SID"),
  Channel_partner_id: envString("Channel_partner_id"),
  ImportCount: envNum("ImportCount"),
  ImportLocation: envString("ImportLocation"),
  SVPickupLocation_1: envString("SVPickupLocation_1"),
  SVPickupLocation_2: envString("SVPickupLocation_2"),
  DownloadLocation: envString("DownloadLocation"),
  extension: envString("extension"),
  SMS_Template_Name: envString("SMS_Template_Name"),
  SMS_Template_ID: envString("SMS_Template_ID"),
  SMS_Template_Content: envString("SMS_Template_Content"),
  SMS_Template_Type: envString("SMS_Template_Type"),
  GrowAasan: envString("GrowAasan"),
  ADZ: envString("ADZ"),
  Email_Template_ID: envString("Email_Template_ID"),
  Email_Template_Name: envString("Email_Template_Name"),
  Email_Template_Subject: envString("Email_Template_Subject"),
  UserToAssignLeadEmail: envString("UserToAssignLeadEmail"),
  UserToAssignLeadID: envString("UserToAssignLeadID"),
  FromPresales: envString("FromPresales"),
  PendingSiteVisits: envString("PendingSiteVisits"),
  PendingFollowUps: envString("PendingFollowUps"),
  AllLeadsPage: envString("AllLeadsPage"),
  api_project: envString("api_project"),
  api_searchlist_from_presales: envString("api_searchlist_from_presales"),
  api_teamId: envString("api_teamId"),
  api_sales_dump: envString("api_sales_dump"),
  api_sales_project: envString("api_sales_project"),
  NEW_ENQUIRIES: envString("NEW_ENQUIRIES"),
  UNREAD_EMAILS: envString("UNREAD_EMAILS"),
  UNREAD_WHATSAPP: envString("UNREAD_WHATSAPP"),
  MISSED_CALLS: envString("MISSED_CALLS"),
  NO_FUTURE_ACTIVITY: envString("NO_FUTURE_ACTIVITY"),
  RE_ENGAGED_LEADS: envString("RE_ENGAGED_LEADS"),
  MISSED_FOLLOWUPS: envString("MISSED_FOLLOWUPS"),
  MISSED_SITE_VISITS: envString("MISSED_SITE_VISITS"),
  REASSINGTOME: envString("REASSINGTOME"),
  Email: envString("Email"),
  Export_Gmail: envString("Export_Gmail"),
  Email_Template: envString("Email_Template"),
  Postsales_schemes_template_ID: envString("Postsales_schemes_template_ID"),
  delayTime: envNum("delayTime"),
  WorkflowName: envString("WorkflowName"),
  SystemOwner: envString("SystemOwner"),
  CampeignEmail: envString("CampeignEmail"),
  Domain: envString("Domain"),
  Convemail_id_sales: envString("Convemail_id_sales"),
  Convemail_Name_sales: envString("Convemail_Name_sales"),
  Convemail_email_sales: envString("Convemail_email_sales"),
  Convemail_phone_sales: envString("Convemail_phone_sales"),
  Convecall_id_pre_sales: envString("Convecall_id_pre_sales"),
  Convecall_Name_pre_sales: envString("Convecall_Name_pre_sales"),
  Convecall_email_pre_sales: envString("Convecall_email_pre_sales"),
  Convecall_phone_pre_sales: envString("Convecall_phone_pre_sales"),
  Convsms_id_sales: envString("Convsms_id_sales"),
  Convsms_Name_sales: envString("Convsms_Name_sales"),
  Convsms_email_sales: envString("Convsms_email_sales"),
  Convsms_phone_sales: envString("Convsms_phone_sales"),
  Convesitevisit_id_pre_sales: envString("Convesitevisit_id_pre_sales"),
  Convesitevisit_Name_pre_sales: envString("Convesitevisit_Name_pre_sales"),
  Convesitevisit_email_pre_sales: envString("Convesitevisit_email_pre_sales"),
  Convesitevisit_phone_pre_sales: envString("Convesitevisit_phone_pre_sales"),
  Convefollowup_id_sales: envString("Convefollowup_id_sales"),
  Convefollowup_Name_sales: envString("Convefollowup_Name_sales"),
  Convefollowup_email_sales: envString("Convefollowup_email_sales"),
  Convefollowup_phone_sales: envString("Convefollowup_phone_sales"),
  Convwhatspp_id_sales: envString("Convwhatspp_id_sales"),
  Convwhatspp_Name_sales: envString("Convwhatspp_Name_sales"),
  Convwhatspp_email_sales: envString("Convwhatspp_email_sales"),
  Convwhatspp_phone_sales: envString("Convwhatspp_phone_sales"),
  Convebulkc2c_id_manager: envString("Convebulkc2c_id_manager"),
  Convebulkc2c_Name_manager: envString("Convebulkc2c_Name_manager"),
  Convebulkc2c_email_manager: envString("Convebulkc2c_email_manager"),
  Convebulkc2c_phone_manager: envString("Convebulkc2c_phone_manager"),
  Project_Duplicate_Admin_Email: envString("Project_Duplicate_Admin_Email"),
  Project_Duplicate_Sales_Email: envString("Project_Duplicate_Sales_Email"),
  Project_Duplicate_Sales_Name: envString("Project_Duplicate_Sales_Name"),
  Project_Duplicate_Sales_Id: envString("Project_Duplicate_Sales_Id"),
  Project_Duplicate_Sales_Team: envString("Project_Duplicate_Sales_Team"),
  Project_Duplicate_Project_1_Name: envString("Project_Duplicate_Project_1_Name"),
  Project_Duplicate_Project_1_Id: envString("Project_Duplicate_Project_1_Id"),
  Project_Duplicate_Project_2_Name: envString("Project_Duplicate_Project_2_Name"),
  Project_Duplicate_Project_2_Id: envString("Project_Duplicate_Project_2_Id"),
  Project_Duplicate_FullAccess_API: envString("Project_Duplicate_FullAccess_API"),
  Project_Duplicate_RestrictedAccess_API: envString("Project_Duplicate_RestrictedAccess_API"),
  Project_Duplicate_Client_Id: envString("Project_Duplicate_Client_Id"),
  Project_Duplicate_SRD_1: envString("Project_Duplicate_SRD_1"),
  Project_Duplicate_SRD_1_Name: envString("Project_Duplicate_SRD_1_Name"),
  Project_Duplicate_SRD_2: envString("Project_Duplicate_SRD_2"),
  Project_Duplicate_SRD_3: envString("Project_Duplicate_SRD_3"),
  Project_Duplicate_SRD_2_Name: envString("Project_Duplicate_SRD_2_Name"),
  followupUser_email: envString("followupUser_email"),
  ExportUser: envString("ExportUser"),
  starkclientAdminEmail: envString("starkclientAdminEmail"),
  presaleTeam1User: envString("presaleTeam1User"),
  presaleTeam1Password: envString("presaleTeam1Password"),
  starkclientmanagerEmail: envString("starkclientmanagerEmail"),
  starkclientmanagerPassword: envString("starkclientmanagerPassword"),
  Dashboard_Sale_id: envString("Dashboard_Sale_id"),
  Dashboard_Sale_email: envString("Dashboard_Sale_email"),
  Dashboard_Sale_name: envString("Dashboard_Sale_name"),
  Dhananjay_salePhone: envString("Dhananjay_salePhone"),
  leadManagementTestUserEmail: envString("leadManagementTestUserEmail"),
  SV_Sales_email: envString("SV_Sales_email"),
  SV_Sales_id: envString("SV_Sales_id"),
  SV_Team_id: envString("SV_Team_id"),
  SV_Invitee_team: envString("SV_Invitee_team"),
  SV_Client_id: envString("SV_Client_id"),
  APIforVirtualWalkthrough: envString("APIforVirtualWalkthrough"),
  Housing_Pusher_API_Key: envString("Housing_Pusher_API_Key"),
  Roof_And_Floor_API_Key: envString("Roof_And_Floor_API_Key"),
  MagicBricks_API_Key: envString("MagicBricks_API_Key"),
  Commonfloor_Pusher_API_Key: envString("Commonfloor_Pusher_API_Key"),
  NinetyNineAcres_API_Key: envString("NinetyNineAcres_API_Key"),
  Facebook_API_Key: envString("Facebook_API_Key"),
};
